language: python
# Existing Python versions
python:
  - 3.4
  - 3.5
  - 3.6
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install .
  - pip install -r requirements-dev.txt
  - pip install coveralls
script:
  - make tests
  - make quality
after_success:
  - coveralls
